#define PADS_QSPI_BASE 0x40020000
#define   PADS_QSPI_GPIO_QSPI_SCLK_OFFSET 0x4
#define     PADS_QSPI_GPIO_QSPI_SCLK_DRIVE_LSB 4
#define     PADS_QSPI_GPIO_QSPI_SCLK_SLEWFAST_BITS 1<<0
#define   PADS_QSPI_GPIO_QSPI_SD0_OFFSET 0x8
#define     PADS_QSPI_GPIO_QSPI_SD0_SCHMITT_BITS 1<<1
#define   PADS_QSPI_GPIO_QSPI_SD1_OFFSET 0xc
#define   PADS_QSPI_GPIO_QSPI_SD2_OFFSET 0x10
#define   PADS_QSPI_GPIO_QSPI_SD3_OFFSET 0x14

