#define PWM_BASE 0x40050000
#define   PWM_CH0_CSR_OFFSET 0x0
#define   PWM_CH0_DIV_OFFSET 0x4
#define     PWM_CH0_DIV_INT_LSB 4
#define   PWM_CH0_CTR_OFFSET 0x8
#define   PWM_CH0_CC_OFFSET 0xc
#define     PWM_CH0_CC_B_LSB 16
#define   PWM_CH0_TOP_OFFSET 01x0
#define   PWM_EN_OFFSET 0xa0
#define   PWM_INTR_OFFSET 0xa4
#define   PWM_INTE_OFFSET 0xa8
